package pokemon.object;

import java.util.ArrayList;
import java.util.List;

/**
 * Server-authoritative state for one wild battle session. Held in memory by
 * BattleService (battles are short-lived; no DB persistence needed).
 */
public class BattleState {
    private long battleId;
    private int  playerId;
    private long spawnId;
    private double playerLat;
    private double playerLng;

    private BattleCombatant wild;
    private BattleCombatant player;   // currently active player Pokemon

    private int     turnCount;
    private boolean over;
    private String  outcome;          // null | WON | FLED | FAINTED | CAUGHT | LEFT

    // Messages generated by the most recent action only (frontend keeps its own history).
    private transient List<String> log = new ArrayList<>();

    private long lastActivity = System.currentTimeMillis();

    public BattleState() {}

    public long getBattleId() { return battleId; }
    public void setBattleId(long battleId) { this.battleId = battleId; }
    public int getPlayerId() { return playerId; }
    public void setPlayerId(int playerId) { this.playerId = playerId; }
    public long getSpawnId() { return spawnId; }
    public void setSpawnId(long spawnId) { this.spawnId = spawnId; }
    public double getPlayerLat() { return playerLat; }
    public void setPlayerLat(double playerLat) { this.playerLat = playerLat; }
    public double getPlayerLng() { return playerLng; }
    public void setPlayerLng(double playerLng) { this.playerLng = playerLng; }
    public BattleCombatant getWild() { return wild; }
    public void setWild(BattleCombatant wild) { this.wild = wild; }
    public BattleCombatant getPlayer() { return player; }
    public void setPlayer(BattleCombatant player) { this.player = player; }
    public int getTurnCount() { return turnCount; }
    public void setTurnCount(int turnCount) { this.turnCount = turnCount; }
    public void incrementTurn() { this.turnCount++; }
    public boolean isOver() { return over; }
    public void setOver(boolean over) { this.over = over; }
    public String getOutcome() { return outcome; }
    public void setOutcome(String outcome) { this.outcome = outcome; }

    public List<String> getLog() { return log; }
    public void resetLog() { this.log = new ArrayList<>(); }
    public void addLog(String msg) { this.log.add(msg); }

    public long getLastActivity() { return lastActivity; }
    public void touch() { this.lastActivity = System.currentTimeMillis(); }

    /** Catch-rate multiplier from the wild Pokemon's remaining HP — easier the lower it is. */
    public double getCatchBonus() {
        if (wild == null || wild.isFainted()) return 0.0;
        int pct = wild.hpPercent();
        if (pct <= 10) return 2.5;
        if (pct <= 25) return 2.0;
        if (pct <= 50) return 1.5;
        return 1.0;
    }
}
